const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>"$"+Number(v||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
let currentUser=null;
async function api(url,options={}){let r;try{r=await fetch(url,{...options,credentials:"same-origin",cache:"no-store",headers:{"Accept":"application/json",...(options.headers||{})}})}catch{throw new Error("MONARCH CODEX server connection is unavailable. Please refresh and try again.")}const raw=await r.text();let x;try{x=raw?JSON.parse(raw):null}catch{throw new Error("Server returned an invalid response.")}if(!r.ok||!x?.success)throw new Error(x?.message||"Request failed.");return x}
function message(t,type=""){const e=$("#message");if(e){e.textContent=t;e.className="message "+type}}
function closeNav(){const s=$("#memberSidebar"),o=$("#memberOverlay"),b=$("#menuButton");s?.classList.remove("open");o?.classList.remove("open");b?.setAttribute("aria-expanded","false")}
function openNav(){const s=$("#memberSidebar"),o=$("#memberOverlay"),b=$("#menuButton");s?.classList.add("open");o?.classList.add("open");b?.setAttribute("aria-expanded","true")}
async function logout(){try{await api("/api/auth.php?action=logout",{method:"POST"});location.replace("/login.html")}catch(e){message(e.message,"error")}}
function renderIdentity(){document.querySelectorAll("[data-user-name]").forEach(e=>e.textContent=currentUser.name||"Monarch");document.querySelectorAll("[data-user-uid]").forEach(e=>e.textContent=currentUser.uid||"—");const role=currentUser.role||"member";if(role!=="member"){location.replace("/admin.html");return false}return true}
async function init(){try{const x=await api("/api/auth.php?action=me",{method:"POST"});currentUser=x.user;if(!renderIdentity())return;const page=document.body.dataset.page;await loadPage(page)}catch(e){message(e.message,"error");setTimeout(()=>location.replace("/login.html"),1600)}}
async function loadPage(page){
 if(page==="overview")return overview();
 if(page==="kyc")return kyc();
 if(page==="referrals")return referrals();
 if(page==="profile")return profile();
 if(["investment","academy","intelligence","signals"].includes(page))return protectedPage(page);
}
async function overview(){const x=await api("/api/member.php",{method:"POST"}),s=x.summary||{};$("#balance").textContent=money(s.available_balance);$("#earnings").textContent=money(s.earnings);$("#deposited").textContent=money(s.deposited_amount);const k=await api("/api/kyc.php?action=status",{method:"POST"});$("#kycStatus").textContent=(k.kyc?.status||"not_submitted").replace("_"," ")}
async function referrals(){try{const x=await api("/api/referrals.php",{method:"POST"}),d=x.referral||{};$("#refCode").textContent=d.code||"—";$("#refLink").textContent=d.link||"—";$("#refTotal").textContent=(d.total||0)+" REFERRED";$("#refList").innerHTML=d.referrals?.length?d.referrals.map(r=>'<div class="ref"><div><strong>'+esc(r.full_name)+'</strong><small>'+esc(r.uid)+' · Joined '+esc(r.created_at)+'</small></div><span class="'+(r.is_online?"online":"offline")+'">'+(r.is_online?"Online":"Offline")+'</span></div>').join(""):'<div class="locked">No Monarchs have joined through your referral yet.</div>'}catch(e){message(e.message,"error")}}
async function profile(){const x=await api("/api/auth.php?action=me",{method:"POST"}),u=x.user;$("#profileName").textContent=u.name;$("#profileEmail").textContent=u.email;$("#profileUid").textContent=u.uid;$("#profileRole").textContent=u.role||"member";$("#profileJoined").textContent=u.created_at||"—"}
async function protectedPage(page){const x=await api("/api/member.php",{method:"POST"}),approved=!!x.kyc?.approved||String(x.kyc_status||"")=="approved";const names={investment:"Investment",academy:"Academy",intelligence:"Monarch Intelligence",signals:"Signals"};if(approved){$("#protectedStatus").textContent="KYC approved";$("#protectedStatus").className="status online";$("#protectedContent").innerHTML='<div class="section"><h2>'+names[page]+'</h2><p>This member area is ready for its full feature workflow. Your KYC status is approved, so protected access is enabled.</p></div>'}else{$("#protectedStatus").textContent="KYC required";$("#protectedContent").innerHTML='<div class="locked"><strong>'+names[page]+' is locked</strong><p>Complete and receive KYC approval before using this protected MONARCH CODEX service.</p><a class="back" href="/kyc.html">Go to KYC Verification →</a></div>'}}
async function compress(file){if(!file||!file.type.startsWith("image/")||file.size<=1500000)return file;return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=async()=>{try{let side=Math.min(1900,Math.max(im.naturalWidth,im.naturalHeight)),q=.78,blob=null;for(let i=0;i<6;i++){const scale=Math.min(1,side/Math.max(im.naturalWidth,im.naturalHeight)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(im.naturalWidth*scale));c.height=Math.max(1,Math.round(im.naturalHeight*scale));c.getContext("2d",{alpha:false}).drawImage(im,0,0,c.width,c.height);blob=await new Promise(d=>c.toBlob(d,"image/jpeg",q));if(blob&&blob.size<=1500000)break;q=Math.max(.52,q-.08);side=Math.max(1200,Math.round(side*.82))}URL.revokeObjectURL(u);if(!blob||blob.size>1500000)reject(new Error("Please use smaller KYC images (about 1.5MB or less each)."));else resolve(new File([blob],(file.name||"kyc-image").replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg"}))}catch(e){URL.revokeObjectURL(u);reject(e)}};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("One KYC image could not be read."))};im.src=u})}
async function kyc(){const x=await api("/api/kyc.php?action=status",{method:"POST"}),k=x.kyc||{},status=k.status||"not_submitted";$("#kycStatus").textContent=status.replace("_"," ");$("#kycStatus").className="status "+(status==="approved"?"online":"");const form=$("#kycForm");if(status==="approved"){form.hidden=true;$("#kycNotice").textContent="Your KYC is approved. Protected member services are unlocked."}else{$("#kycNotice").textContent=status==="under_review"?"Your KYC is under review.":status==="rejected"?"KYC rejected. Reason: "+(k.rejection_reason||"Please review and resubmit."):"Complete the form below to submit KYC for review.";for(const n of ["first_name","surname","middle_name","email","phone","address","occupation"]){if(form.elements[n])form.elements[n].value=k[n]||currentUser.email&&n==="email"?k[n]||currentUser.email:""}form.elements.nin_number.value="";if(status==="rejected")form.querySelector("button").textContent="Resubmit KYC";}form.addEventListener("submit",async e=>{e.preventDefault();const b=form.querySelector("button");b.disabled=true;b.textContent="Preparing documents…";try{const fd=new FormData(form);for(const n of ["nin_front","nin_back","selfie"]){const f=form.elements[n]?.files?.[0];if(f){const p=await compress(f);fd.delete(n);fd.append(n,p,p.name)}}b.textContent="Submitting…";const r=await api("/api/kyc.php?action=submit",{method:"POST",body:fd});message(r.message||"KYC submitted.","success");setTimeout(()=>location.reload(),700)}catch(e){message(e.message,"error");b.disabled=false;b.textContent="Submit KYC for review"}})}
document.addEventListener("DOMContentLoaded",()=>{const b=$("#menuButton");b?.addEventListener("click",openNav);$("#memberClose")?.addEventListener("click",closeNav);$("#memberOverlay")?.addEventListener("click",closeNav);document.querySelectorAll(".member-nav a").forEach(a=>a.addEventListener("click",closeNav));$("#logout")?.addEventListener("click",logout);$("#headerLogout")?.addEventListener("click",logout);$("#copyCode")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("#refCode").textContent);message("Referral code copied.","success")}catch{}});$("#copyLink")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("#refLink").textContent);message("Referral link copied.","success")}catch{}});init()});
